
name: Build and publish image

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_publish_command:
        required: true
        type: string
    secrets:
      maven_repo_access_token:
        description: 'Maven repo access token'
        required: true
      cr_user:
        description: 'Container registry user'
        required: true
      cr_password:
        description: 'Container registry password'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      # Runs a set of commands using the runners shell
      - name: Preparing build
        env:
          MAVEN_REPO_PAT: ${{ secrets.maven_repo_access_token }}
        run: |
          # Configuring credentials for Gradle connection to Azure Artifacts
          sed -i "s/PERSONAL_ACCESS_TOKEN/$MAVEN_REPO_PAT/g" local.properties-template
          mv local.properties-template local.properties
          cat local.properties
      - name: Build Mobile module
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.build_command }}
      - name: Building and Pushing Docker image
        env:
          DOCKER_IMAGE_NAME: ${{ inputs.image_name }}
          ACR_USERNAME: ${{ secrets.cr_user }}
          ACR_PASSWORD: ${{ secrets.cr_password }}
        uses: gradle/gradle-build-action@v2
        if: success()
        with:
          arguments: ${{ inputs.image_publish_command }}